(define (problem problemaExtension1)
 (:domain dominioExtension1)

 (:objects
   hab1  -habitacion
   res1 res2 res3 res4 res5 res6 - reserva
 )

 (:init
   (not (resuelta res1))
   (not (resuelta res2))
   (not (resuelta res3))
   (not (resuelta res4))
   (not (resuelta res5))
   (not (resuelta res6))
   (= (reservasNoAsignadadas) 0)
   (= (plazas hab1) 4)
   (= (personas res1) 1)
   (= (inicio res1) 1)
   (= (fin res1) 30)
   (= (personas res2) 4)
   (= (inicio res2) 2)
   (= (fin res2) 3)
   (= (personas res3) 3)
   (= (inicio res3) 4)
   (= (fin res3) 5)
   (= (personas res4) 3)
   (= (inicio res4) 6)
   (= (fin res4) 7)
   (= (personas res5) 3)
   (= (inicio res5) 8)
   (= (fin res5) 9)
   (= (personas res6) 4)
   (= (inicio res6) 24)
   (= (fin res6) 25)
 )
 (:goal
   (forall (?res - reserva) (resuelta?res))
 )
(:metric minimize (reservasNoAsignadadas))
)
