(define (problem problemaExtension4)
 (:domain dominioExtension4)
 (:objects
   hab1 hab2  - habitacion
   res1 res2 res3 res4 res5 res6 - reserva
 )
 (:init
   (not (resuelta res1))
   (not (resuelta res2))
   (not (resuelta res3))
   (not (resuelta res4))
   (not (resuelta res5))
   (not (resuelta res6))
   (= (reservasNoAsignadas) 0)
   (= (plazasMalgastadas) 0)
   (= (habitacionesDiferentes) 0)
   (= (plazas hab1) 4)
   (= (plazas hab2) 1)
   (= (personas res1) 1)
   (= (inicio res1) 1)
   (= (fin res1) 2)
   (= (personas res2) 4)
   (= (inicio res2) 3)
   (= (fin res2) 4)
   (= (personas res3) 3)
   (= (inicio res3) 5)
   (= (fin res3) 6)
   (= (personas res4) 3)
   (= (inicio res4) 7)
   (= (fin res4) 8)
   (= (personas res5) 2)
   (= (inicio res5) 9)
   (= (fin res5) 10)
   (= (personas res6) 1)
   (= (inicio res6) 11)
   (= (fin res6) 12)
 )
 (:goal
   (forall (?res - reserva) (resuelta?res))
 )
   (:metric minimize (+ (+ (* (reservasNoAsignadas) 54) (plazasMalgastadas)) (* (habitacionesDiferentes) 18)))
)
